### ISSUE TITLE
Images are not opening in lightbox

### ISSUE THREAD

**Issue by bartoszwanot** [getgrav/grav-plugin-featherlight#16]
Hi guys,

I've got problem with Featherlight plugin and I don't have idea how to fix it, so maybe you will be able to help me. 
I'm using Grav v1.2.4 with Grav Admin v1.4.2 and Clean Blog template. I've installed and activated Featherlight plugin as the manual says. However it's not working as it should - images are showing in the tab, not in the lightbox as it should. You can check it here: http://sugoi.com.pl/beta/new-nintendo-2ds-xl-odswiezona-przenosna-konsola (images are at the end of the article).

Code in the article is:
`![](2ds-dq2.jpg?lightbox=1024&cropResize=200,200) ![](2ds-dq1.jpg?lightbox=1024&cropResize=200,200) ![](2ds-dq3.jpg?lightbox=1024&cropResize=200,200)`

And here is configuration of Featherlight from featherlight.yaml file:
```
enabled: true                 # global enable/disable the entire plugin
active: true                  # if the plugin is active and JS/CSS should be loaded
gallery: false                # enable/disable the gallery extension
requirejs: false              # output to an AMD module
openSpeed: 250                # open speed in ms
closeSpeed: 250               # close speed in ms
closeOnClick: background      # background|anywhere|false
closeOnEsc: true              # true|false on hitting Esc key
root: body                    # where to append featherlights
initTemplate: plugin://featherlight/js/featherlight.init.js
```

Any ideas what I have done wrong?

**Comment by flaviocopes** [comment]
It does show in the lightbox for me. Did you solve the issue?

**Comment by bartoszwanot** [comment]
Not me, but the author of Clean Blog Template - there was an error on template side, which was fixed yesterday.
