### ISSUE TITLE
Images have '@1x' burned in 

### ISSUE THREAD

**Issue by gurahamu** [getgrav/grav-plugin-featherlight#22]
Hi, 
On all images when using Featherlite, I see '@1x' burned in to the top left corner. Is this working as designed? Can I turn this off?

Example:  `![](piHAT1-1200.jpg?lightbox=1200&resize=600)`
[image](https://www.brightblack.net/images/9/a/6/b/9/9a6b98b1b00de9d9da9e0b8734154615e5704fee-pihat1-1200.jpeg)

(Apologies if this is a feature and I'm just misusing the plugin as I don't use many images.)

**Comment by rhukster** [comment]
Just set the "debug" option in the "images" section of Grav's System config to `false`
