### ISSUE TITLE
Plugin doesn't seem to work, not even on Grav wiki

### ISSUE THREAD

**Issue by Japhys** [getgrav/grav-plugin-featherlight#23]
Hi,

I cannot get this to work. Tried different things, themes, browsers, doesn't work anywhere. 

But it doesn't work on Grav docs (media) either:

https://learn.getgrav.org/16/content/media#lightbox

Am I missing something here?

**Comment by rhukster** [comment]
You need to install "featherlight" plugin.  I had forgotten to do this on the new learn site myself.  Fixed now.

**Comment by Japhys** [comment]
Hmm I did :) 
![Screenshot(3)](https://user-images.githubusercontent.com/24695937/58382563-2e65f300-7fcc-11e9-9812-9203567542c4.png)

Could it be the theme?

**Comment by rhukster** [comment]
it's possible.  Check to make sure the CSS/JS and the inline JS for initializing the lightbox is in your page output.

**Comment by Japhys** [comment]
Driving me nuts :) Can't see the problem. On this test page all seems to be fine

http://once.ly/voOB8

**Comment by Japhys** [comment]
@rhukster Would you mind terribly to have a look? I tried pretty much everything I can, installed it throught command line, admin panel. Checked persmissions etc. All seems okay. I am not a developer so I don't know how to debug this really.

Thanks a million

**Comment by rhukster** [comment]
I think you have `requirejs: true` set in your featherlight config, set that to `false`.

**Comment by Japhys** [comment]
Thanks Andy, did that in admin panel, but noticed my featherlight.yaml still read:

`enabled: true                 # global enable/disable the entire plugin
active: true                  # if the plugin is active and JS/CSS should be loaded
gallery: enable                # enable/disable the gallery extension
requirejs: true              # output to an AMD module
openSpeed: 250                # open speed in ms
closeSpeed: 250               # close speed in ms
closeOnClick: background      # background|anywhere|false
closeOnEsc: true              # true|false on hitting Esc key
root: body                    # where to append featherlights
initTemplate: plugin://featherlight/js/featherlight.init.js`

Which is weird. I woud expect this admin panel button to change the yaml file.

Anyway both are on false now. But clicking on the image doesn't do anything now.

This is correct right?: .....jpg?lightbox=600,400&resize=200,200

**Comment by Japhys** [comment]
Did a clean install, tried featherlight in default theme. Worked! Installed Grav coder. Tried featherlight. Didn't work. Well it's the theme afterall.

**Comment by Japhys** [comment]
In case I can be of any help to other users..

I checked in Chrome dev tools

```
Uncaught TypeError: c.$instance.fadeIn is not a function
    at b.open (featherlight.min.js:8)
    at HTMLAnchorElement.i (featherlight.min.js:8)
    at HTMLAnchorElement.dispatch (jquery-slim.min.js:2)
    at HTMLAnchorElement.v.handle (jquery-slim.min.js:2)
open @ featherlight.min.js:8
i @ featherlight.min.js:8
dispatch @ jquery-slim.min.js:2
v.handle @ jquery-slim.min.js:2
```

So I replaced the slim for the full version in the Grav Coder theme and then it worked
