### ISSUE TITLE
Minor 

### ISSUE THREAD

**Issue by mikegcox** [getgrav/grav-plugin-featherlight#3]
There is a minor issue with documentation in the Readme file.

```
![Sample Image](sample-image.jpg?lightbox=1024,cropResize=200,200)
```

Should be:

```
![Sample Image](sample-image.jpg?lightbox=1024&cropResize=200,200)
```

There is a comma in the querystring part of the file path that should be an ampersand.

**Comment by rhukster** [comment]
If you edit the README directly on Github.com, it will automatically create a PR, and you'll get the credit for the fix :)

**Comment by mikegcox** [comment]
Cool, sory for being a nube… I have somehow managed to not know anything about git, so thanks for helping.

**Comment by rhukster** [comment]
No problem, we were all there at one point!

**Comment by mikegcox** [comment]
I hope I did that right.  Thanks again.

**Comment by rhukster** [comment]
Yup, was fine :) I see Ryan already merged it!
