### ISSUE TITLE
Opens Image in new page only

### ISSUE THREAD

**Issue by ghost** [getgrav/grav-plugin-featherlight#5]
Greetings,

so, in markdown I put ...

`![logo](../logo.png?lightbox)`

But all it does is open the logo in a new window, no lightbox. Suggestions?

**Comment by seebz** [comment]
As said in the [README](https://github.com/getgrav/grav-plugin-featherlight/blob/develop/README.md#configuration) :

> Featherlight is **enabled** but **not active** by default.

Simply RTFM <sup>[(?)](http://en.wikipedia.org/wiki/RTFM)</sup> to know how activate the plugin.
<sub>(hoping this comment will help future users)</sub>
