### ISSUE TITLE
Broken links inside featherbox

### ISSUE THREAD

**Issue by pithp** [getgrav/grav-plugin-featherlight#8]
When I click on an image the lightbox opens, the previus and next arrows apear but dont work.
tryed from the .md file and in the .twig : 

forum link :
http://getgrav.org/forum#!/plugin-development:problem-to-set-featherbox-g

**Comment by flaviocopes** [comment]
I cannot recreate this on other themes, and on Twentyfifteen, the one you mention in the forum post, featherlight does not work fine to me, from a quick look. Does it happen on any other theme? Might be a theme compatibility issue.
