### ISSUE TITLE
Change default for 'active' to true?

### ISSUE THREAD

**Issue by paulhibbitts** [getgrav/grav-plugin-featherlight#9]
How about the default 'active' setting is changed to true for this plugin? I know this is stated in the ReadMe but if one installs this plugin wouldn't the expected behavior be to 'work out of the box' rather than needing additional config for such a simple thing like lightbox functionality?

Thanks for considering this request!

**Comment by rhukster** [comment]
Probably makes sense 👍 

Changed.

**Comment by paulhibbitts** [comment]
Thanks very much Andy! Once it is released I will make the needed changes to the ReadMe as well.
